CREATE TABLE cart2 (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
teaName VARCHAR(30) NOT NULL,
sizeName VARCHAR(30) NOT NULL,
addIn VARCHAR(30) NOT NULL,
Toppings VARCHAR(30) NOT NULL,
Flavors VARCHAR(30) NOT NULL,
CupOptions VARCHAR(30) NOT NULL,
teaPrice DECIMAL (3,2) NOT NULL
);
